# Adds namespace to all resources.
namespace: kyma-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: dockerregistry-

# Labels to add to all resources.
labels:
  - pairs:
      kyma-project.io/module: dockerregistry-operator
      app.kubernetes.io/name: dockerregistry-operator
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/part-of: dockerregistry-operator
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - ./crd
  - ./deployment
  - ./rbac
  - ./ui-extensions
