# permissions for end users to view dockerregistry.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: dockerregistry-operator-viewer-role
    app.kubernetes.io/component: rbac
  name: operator-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - dockerregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - dockerregistries/status
  verbs:
  - get
